spring.application.name=syllogi

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.h2.console.path=/h2-console

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#spring.datasource.url=jdbc:h2:mem:test
spring.datasource.url=jdbc:h2:file:C:/Users/USER/test
spring.datasource.username=sa
spring.datasource.password=

spring.autoconfigure.include=org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
#hibernate.transaction.jta.platform=enable
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
